-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  changes jsonb,
  ip_address text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  drug_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT cart_items_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES public.otc_drugs(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  participant_ids ARRAY NOT NULL,
  subject character varying,
  conversation_type character varying DEFAULT 'direct'::character varying CHECK (conversation_type::text = ANY (ARRAY['direct'::character varying, 'group'::character varying]::text[])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.doctor_patient_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT doctor_patient_links_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_patient_links_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES auth.users(id),
  CONSTRAINT doctor_patient_links_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES auth.users(id)
);
CREATE TABLE public.doctor_prescriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL,
  patient_id uuid,
  duration text,
  instructions text,
  notes text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'processing'::text, 'partially_filled'::text, 'filled'::text, 'refill_requested'::text])),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  prescription_number text NOT NULL DEFAULT ''::text UNIQUE,
  filled_at timestamp with time zone,
  pharmacist_name text,
  file_url text,
  file_name text,
  medication_name text,
  dosage text,
  refills_allowed integer DEFAULT 0,
  rejection_reason text,
  admin_notes text,
  doctor_name text,
  doctor_phone text,
  doctor_email text,
  practice_name text,
  refill_count integer DEFAULT 0,
  refill_limit integer DEFAULT 5,
  last_refilled_at timestamp without time zone,
  is_refillable boolean DEFAULT false,
  refill_status character varying DEFAULT 'active'::character varying,
  practice_street_line_1 text,
  practice_street_line_2 text,
  practice_city text,
  practice_state text,
  practice_postal_code text,
  practice_country text DEFAULT 'Jamaica'::text,
  CONSTRAINT doctor_prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_prescriptions_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT doctor_prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id)
);
CREATE TABLE public.doctor_prescriptions_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_prescription_id uuid NOT NULL,
  medication_name text NOT NULL,
  dosage text,
  quantity integer,
  brand_choice text DEFAULT 'generic'::text CHECK (brand_choice = ANY (ARRAY['brand'::text, 'generic'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  duration text,
  frequency text,
  medication_id uuid,
  price numeric,
  total_amount numeric,
  quantity_filled integer DEFAULT 0,
  CONSTRAINT doctor_prescriptions_items_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_prescriptions_items_doctor_prescription_id_fkey FOREIGN KEY (doctor_prescription_id) REFERENCES public.doctor_prescriptions(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipientemail text NOT NULL,
  subject text NOT NULL,
  templatetype text,
  status text DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text, 'bounced'::text, 'opened'::text, 'clicked'::text])),
  sentat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  failurereason text,
  messageid text UNIQUE,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  orderupdates boolean DEFAULT true,
  prescriptionupdates boolean DEFAULT true,
  promotionalemails boolean DEFAULT false,
  weeklynewsletter boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT email_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  type text NOT NULL CHECK (type = ANY (ARRAY['order_confirmation'::text, 'order_shipped'::text, 'prescription_approved'::text, 'refill_approved'::text, 'refill_rejected'::text, 'password_reset'::text, 'verification'::text, 'custom'::text])),
  subject text NOT NULL,
  htmlcontent text NOT NULL,
  textcontent text,
  variables ARRAY DEFAULT '{}'::text[],
  enabled boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  drug_id uuid NOT NULL,
  drug_type text NOT NULL CHECK (drug_type = ANY (ARRAY['otc'::text, 'prescription'::text])),
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['adjustment'::text, 'purchase'::text, 'sale'::text, 'expiration'::text, 'damage'::text])),
  quantity_change integer NOT NULL,
  quantity_before integer NOT NULL,
  quantity_after integer NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.message_reads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT message_reads_pkey PRIMARY KEY (id),
  CONSTRAINT message_reads_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT message_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  attachment_url character varying,
  attachment_type character varying,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  read_by ARRAY DEFAULT '{}'::uuid[],
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  drug_id uuid,
  drug_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric,
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  pharm_confirm boolean DEFAULT false,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES public.otc_drugs(id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_number text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'payment_pending'::text, 'payment_submitted'::text, 'payment_verified'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text])),
  total_amount numeric NOT NULL,
  subtotal_amount numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  shipping_amount numeric DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  payment_status character varying DEFAULT 'unpaid'::character varying,
  payment_method character varying,
  receipt_url text,
  transaction_id uuid,
  is_prescription_order boolean DEFAULT false,
  prescription_id uuid,
  doctor_prescription_id uuid,
  shipping_street_line_1 text,
  shipping_street_line_2 text,
  shipping_city text,
  shipping_state text,
  shipping_postal_code text,
  shipping_country text DEFAULT 'Jamaica'::text,
  billing_street_line_1 text,
  billing_street_line_2 text,
  billing_city text,
  billing_state text,
  billing_postal_code text,
  billing_country text DEFAULT 'Jamaica'::text,
  shipping_collect_on_delivery boolean DEFAULT false,
  shipping_estimated_amount numeric,
  shipping_custom_rate numeric,
  shipping_paid_online boolean DEFAULT false,
  shipping_custom_rate_collect_on_delivery boolean DEFAULT false,
  collect_shipping_after_payment boolean DEFAULT false,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id),
  CONSTRAINT orders_doctor_prescription_id_fkey FOREIGN KEY (doctor_prescription_id) REFERENCES public.doctor_prescriptions(id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT orders_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.otc_drugs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  category text NOT NULL,
  sub_category text NOT NULL,
  manufacturer text,
  sku text NOT NULL UNIQUE,
  quantity_on_hand integer NOT NULL DEFAULT 0,
  reorder_level integer NOT NULL DEFAULT 10,
  reorder_quantity integer NOT NULL DEFAULT 50,
  unit_price numeric NOT NULL,
  cost_price numeric,
  description text,
  indications text,
  warnings text,
  side_effects text,
  dosage text,
  active_ingredient text,
  strength text,
  pack_size text,
  expiration_date date,
  lot_number text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'discontinued'::text, 'out_of_stock'::text])),
  low_stock_alert boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  file_url text,
  category_type character varying DEFAULT 'regular'::character varying CHECK (category_type::text = ANY (ARRAY['regular'::character varying, 'sale'::character varying, 'clearance'::character varying]::text[])),
  sale_price numeric,
  sale_discount_percent integer,
  sale_start_date timestamp with time zone,
  sale_end_date timestamp with time zone,
  is_on_sale boolean DEFAULT false,
  pharm_confirm boolean DEFAULT false,
  CONSTRAINT otc_drugs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_holder character varying NOT NULL,
  bank_name character varying NOT NULL,
  account_number character varying NOT NULL,
  routing_number character varying,
  iban character varying,
  swift_code character varying,
  additional_instructions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tax_type text DEFAULT 'inclusive'::text CHECK (tax_type = ANY (ARRAY['none'::text, 'inclusive'::text])),
  tax_rate numeric DEFAULT 15,
  kingston_delivery_cost numeric DEFAULT 0,
  default_shipping_cost numeric DEFAULT 0,
  CONSTRAINT payment_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prescription_drugs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  category text NOT NULL,
  sub_category text NOT NULL,
  manufacturer text,
  sku text NOT NULL UNIQUE,
  quantity_on_hand integer NOT NULL DEFAULT 0,
  reorder_level integer NOT NULL DEFAULT 20,
  reorder_quantity integer NOT NULL DEFAULT 100,
  unit_price numeric NOT NULL,
  cost_price numeric,
  description text,
  indications text,
  warnings text,
  side_effects text,
  dosage text,
  active_ingredient text,
  strength text,
  pack_size text,
  requires_refrigeration boolean DEFAULT false,
  controlled_substance boolean DEFAULT false,
  expiration_date date,
  lot_number text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'discontinued'::text, 'out_of_stock'::text])),
  low_stock_alert boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  file_url text,
  category_type character varying DEFAULT 'regular'::character varying CHECK (category_type::text = ANY (ARRAY['regular'::character varying, 'sale'::character varying, 'clearance'::character varying]::text[])),
  sale_price numeric,
  sale_discount_percent integer,
  sale_start_date timestamp with time zone,
  sale_end_date timestamp with time zone,
  is_on_sale boolean DEFAULT false,
  CONSTRAINT prescription_drugs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prescription_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  medication_id uuid,
  brand_choice text DEFAULT 'generic'::text CHECK (brand_choice = ANY (ARRAY['brand'::text, 'generic'::text])),
  quantity integer NOT NULL,
  price numeric,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  medication_name text,
  dosage text,
  quantity_filled integer DEFAULT 0,
  total_amount integer,
  doctor_prescription_id uuid,
  CONSTRAINT prescription_items_pkey PRIMARY KEY (id),
  CONSTRAINT prescription_items_doctor_prescription_id_fkey FOREIGN KEY (doctor_prescription_id) REFERENCES public.doctor_prescriptions(id),
  CONSTRAINT prescription_items_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id)
);
CREATE TABLE public.prescriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  doctor_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'filled'::text, 'partially_filled'::text, 'dispensing'::text, 'processing'::text, 'refill_requested'::text])),
  file_url text NOT NULL,
  quantity integer,
  refills_allowed integer DEFAULT 0,
  notes text,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  prescription_number text NOT NULL DEFAULT ''::text UNIQUE,
  doctor_name text,
  doctor_phone text,
  doctor_email text,
  practice_name text,
  admin_notes text,
  filled_at timestamp with time zone,
  pharmacist_name text,
  refill_count integer DEFAULT 0,
  refill_limit integer DEFAULT 5,
  last_refilled_at timestamp without time zone,
  is_refillable boolean DEFAULT false,
  refill_status character varying DEFAULT 'active'::character varying,
  practice_street_line_1 text,
  practice_street_line_2 text,
  practice_city text,
  practice_state text,
  practice_postal_code text,
  practice_country text DEFAULT 'Jamaica'::text,
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id),
  CONSTRAINT prescriptions_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.purchase_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  restock_request_id uuid,
  restock_item_id uuid,
  product_id uuid NOT NULL,
  product_type text NOT NULL CHECK (product_type = ANY (ARRAY['otc'::text, 'prescription'::text])),
  product_name text NOT NULL,
  quantity_ordered integer NOT NULL CHECK (quantity_ordered > 0),
  quantity_received integer DEFAULT 0 CHECK (quantity_received >= 0),
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_items_restock_request_id_fkey FOREIGN KEY (restock_request_id) REFERENCES public.restock_requests(id),
  CONSTRAINT purchase_order_items_restock_item_id_fkey FOREIGN KEY (restock_item_id) REFERENCES public.restock_items(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  po_number text NOT NULL UNIQUE,
  supplier_id uuid NOT NULL,
  created_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'placed'::text, 'received'::text, 'cancelled'::text])),
  reorder_date date NOT NULL,
  is_custom_reorder_date boolean DEFAULT false,
  total_amount numeric DEFAULT 0,
  notes text,
  received_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  expected_delivery_date date,
  placed_at timestamp with time zone,
  source text NOT NULL DEFAULT 'scheduled'::text CHECK (source = ANY (ARRAY['scheduled'::text, 'manual'::text])),
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.refill_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  requested_at timestamp without time zone NOT NULL DEFAULT now(),
  approved_at timestamp without time zone,
  approved_by uuid,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  notes text,
  reason text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT refill_requests_pkey PRIMARY KEY (id),
  CONSTRAINT refill_requests_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id),
  CONSTRAINT refill_requests_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id),
  CONSTRAINT refill_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.refills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  refill_number integer NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'requested'::text, 'approved'::text, 'rejected'::text])),
  requested_at timestamp with time zone,
  approved_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT refills_pkey PRIMARY KEY (id),
  CONSTRAINT refills_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id),
  CONSTRAINT refills_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id)
);
CREATE TABLE public.restock_frequencies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  days_interval integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT restock_frequencies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.restock_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restock_request_id uuid NOT NULL,
  action text NOT NULL,
  old_status text,
  new_status text,
  changed_by uuid NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT restock_history_pkey PRIMARY KEY (id),
  CONSTRAINT restock_history_restock_request_id_fkey FOREIGN KEY (restock_request_id) REFERENCES public.restock_requests(id),
  CONSTRAINT restock_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.restock_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restock_request_id uuid NOT NULL,
  product_id uuid NOT NULL,
  product_type text NOT NULL CHECK (product_type = ANY (ARRAY['otc'::text, 'prescription'::text])),
  product_name text NOT NULL,
  quantity_requested integer NOT NULL CHECK (quantity_requested > 0),
  quantity_received integer DEFAULT 0,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  purchase_order_item_id uuid,
  CONSTRAINT restock_items_pkey PRIMARY KEY (id),
  CONSTRAINT restock_items_restock_request_id_fkey FOREIGN KEY (restock_request_id) REFERENCES public.restock_requests(id),
  CONSTRAINT restock_items_purchase_order_item_id_fkey FOREIGN KEY (purchase_order_item_id) REFERENCES public.purchase_order_items(id)
);
CREATE TABLE public.restock_notification_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  notification_email text,
  whatsapp_notifications_enabled boolean NOT NULL DEFAULT false,
  sms_notifications_enabled boolean NOT NULL DEFAULT false,
  app_toast_notifications_enabled boolean NOT NULL DEFAULT true,
  push_notifications_enabled boolean NOT NULL DEFAULT false,
  CONSTRAINT restock_notification_settings_pkey PRIMARY KEY (id),
  CONSTRAINT restock_notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.restock_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_number text NOT NULL UNIQUE,
  supplier_id uuid NOT NULL,
  pharmacist_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['requested'::text, 'linked_to_po'::text, 'received'::text, 'cancelled'::text])),
  total_amount numeric,
  requested_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  approved_at timestamp with time zone,
  approved_by uuid,
  actual_delivery_date date,
  rejection_reason text,
  approval_notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  purchase_order_id uuid,
  CONSTRAINT restock_requests_pkey PRIMARY KEY (id),
  CONSTRAINT restock_requests_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT restock_requests_pharmacist_id_fkey FOREIGN KEY (pharmacist_id) REFERENCES public.users(id),
  CONSTRAINT restock_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT restock_requests_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.shipping_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parish character varying NOT NULL,
  city_town character varying,
  rate numeric NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shipping_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.supplier_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supplier_id uuid NOT NULL,
  product_id uuid NOT NULL,
  product_type text NOT NULL CHECK (product_type = ANY (ARRAY['otc'::text, 'prescription'::text])),
  supplier_sku text,
  supplier_unit_price numeric NOT NULL,
  minimum_order_quantity integer DEFAULT 1,
  reorder_frequency_id uuid,
  last_ordered_at timestamp with time zone,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  product_name text,
  is_inventory_item boolean NOT NULL DEFAULT true,
  CONSTRAINT supplier_products_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT supplier_products_frequency_id_fkey FOREIGN KEY (reorder_frequency_id) REFERENCES public.restock_frequencies(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  contact_person text,
  email text,
  phone text,
  address text,
  city text,
  country text DEFAULT 'Jamaica'::text,
  payment_terms text,
  lead_time_days integer DEFAULT 3,
  minimum_order_amount numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  reorder_schedule_type text CHECK (reorder_schedule_type = ANY (ARRAY['daily'::text, 'weekly'::text, 'bi_weekly'::text, 'three_weeks'::text, 'monthly'::text, 'custom'::text])),
  reorder_schedule_start_date date,
  reorder_schedule_custom_dates ARRAY DEFAULT '{}'::date[],
  reorder_schedule_is_recurring boolean DEFAULT false,
  reorder_schedule_notes text,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  name text NOT NULL,
  content text NOT NULL,
  is_approved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT testimonials_pkey PRIMARY KEY (id),
  CONSTRAINT testimonials_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['payment'::character varying, 'refund'::character varying, 'adjustment'::character varying, 'credit'::character varying]::text[])),
  method character varying NOT NULL CHECK (method::text = ANY (ARRAY['card'::character varying, 'bank_transfer'::character varying, 'cash'::character varying, 'insurance'::character varying, 'wallet'::character varying]::text[])),
  amount numeric NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  reference_id character varying,
  description text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone text,
  city text,
  state text,
  zip text,
  avatar_url text,
  date_of_birth date,
  license_number text,
  license_state text,
  specialty text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  street_address_line_1 text,
  street_address_line_2 text,
  country text DEFAULT 'Jamaica'::text,
  postal_code text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text,
  role text NOT NULL DEFAULT 'patient'::text CHECK (role = ANY (ARRAY['patient'::text, 'admin'::text, 'doctor'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);