-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.allergies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  allergen text NOT NULL,
  reaction text,
  severity text,
  onset_date date,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT allergies_pkey PRIMARY KEY (id),
  CONSTRAINT allergies_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT allergies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id),
  CONSTRAINT allergies_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  clinician_id uuid NOT NULL,
  scheduled_at timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 30,
  appointment_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'scheduled'::appointment_status,
  location text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT appointments_clinician_id_fkey FOREIGN KEY (clinician_id) REFERENCES public.clinicians(id),
  CONSTRAINT appointments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id),
  CONSTRAINT appointments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL,
  old_values jsonb,
  new_values jsonb,
  performed_by uuid,
  performed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.clinicians (
  id uuid NOT NULL,
  full_name text NOT NULL,
  specialty text,
  license_number text,
  phone text,
  role USER-DEFINED NOT NULL DEFAULT 'clinician'::user_role,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  email text,
  CONSTRAINT clinicians_pkey PRIMARY KEY (id),
  CONSTRAINT clinicians_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  visit_id uuid,
  document_type text NOT NULL,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size bigint,
  content_type text,
  description text,
  document_date date,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT documents_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.clinicians(id),
  CONSTRAINT documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id),
  CONSTRAINT documents_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.labs_ordered (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  visit_id uuid,
  patient_id uuid NOT NULL,
  clinician_id uuid NOT NULL,
  lab_test_name text NOT NULL,
  lab_test_code text,
  special_instructions text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::order_status,
  sent_at timestamp with time zone,
  results_received_at timestamp with time zone,
  results jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT labs_ordered_pkey PRIMARY KEY (id),
  CONSTRAINT labs_ordered_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT labs_ordered_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT labs_ordered_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT labs_ordered_clinician_id_fkey FOREIGN KEY (clinician_id) REFERENCES public.clinicians(id),
  CONSTRAINT labs_ordered_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.medical_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  condition text NOT NULL,
  diagnosis_date date,
  status text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT medical_history_pkey PRIMARY KEY (id),
  CONSTRAINT medical_history_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT medical_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id),
  CONSTRAINT medical_history_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.medications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  medication_name text NOT NULL,
  dosage text,
  frequency text,
  route text,
  start_date date,
  end_date date,
  prescriber text,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT medications_pkey PRIMARY KEY (id),
  CONSTRAINT medications_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT medications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id),
  CONSTRAINT medications_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.medications_prescribed (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  visit_id uuid,
  patient_id uuid NOT NULL,
  clinician_id uuid NOT NULL,
  medication_name text NOT NULL,
  dosage text NOT NULL,
  form text,
  frequency text NOT NULL,
  route text,
  quantity integer,
  refills integer DEFAULT 0,
  instructions text,
  pharmacy_name text,
  pharmacy_phone text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::order_status,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT medications_prescribed_pkey PRIMARY KEY (id),
  CONSTRAINT medications_prescribed_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT medications_prescribed_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT medications_prescribed_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT medications_prescribed_clinician_id_fkey FOREIGN KEY (clinician_id) REFERENCES public.clinicians(id),
  CONSTRAINT medications_prescribed_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.message_threads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject text NOT NULL,
  participants ARRAY NOT NULL,
  patient_id uuid,
  last_message_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_threads_pkey PRIMARY KEY (id),
  CONSTRAINT message_threads_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  message_type USER-DEFINED NOT NULL,
  subject text,
  body text NOT NULL,
  priority text DEFAULT 'normal'::text,
  patient_id uuid,
  visit_id uuid,
  thread_id uuid,
  read_at timestamp with time zone,
  archived_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.clinicians(id),
  CONSTRAINT messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.clinicians(id),
  CONSTRAINT messages_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT messages_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid,
  patient_id uuid NOT NULL,
  clinician_id uuid NOT NULL,
  order_type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::order_status,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  sent_at timestamp with time zone,
  completed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT orders_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT orders_clinician_id_fkey FOREIGN KEY (clinician_id) REFERENCES public.clinicians(id),
  CONSTRAINT orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.patient_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  shared_by uuid NOT NULL,
  shared_with uuid NOT NULL,
  permission_level USER-DEFINED NOT NULL DEFAULT 'read'::permission_level,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT patient_shares_pkey PRIMARY KEY (id),
  CONSTRAINT patient_shares_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_shares_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES public.clinicians(id),
  CONSTRAINT patient_shares_shared_with_fkey FOREIGN KEY (shared_with) REFERENCES public.clinicians(id)
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinician_id uuid,
  first_name text NOT NULL,
  last_name text NOT NULL,
  date_of_birth date NOT NULL,
  gender text,
  national_id text,
  email text,
  phone text,
  address text,
  city text,
  parish text,
  postal_code text,
  country text DEFAULT 'Jamaica'::text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  blood_type text,
  occupation text,
  marital_status text,
  smoking_status text,
  alcohol_use text,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  passport_number text,
  drivers_license text,
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT patients_clinician_id_fkey FOREIGN KEY (clinician_id) REFERENCES public.clinicians(id),
  CONSTRAINT patients_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id),
  CONSTRAINT patients_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.transcription_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid,
  audio_path text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::transcription_status,
  transcript_text text,
  word_timestamps jsonb DEFAULT '[]'::jsonb,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  created_by uuid,
  CONSTRAINT transcription_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT transcription_jobs_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT transcription_jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.visit_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid NOT NULL,
  chief_complaint text,
  history_present_illness text,
  review_of_systems jsonb DEFAULT '{}'::jsonb,
  vitals jsonb DEFAULT '{}'::jsonb,
  physical_exam jsonb DEFAULT '{}'::jsonb,
  assessment text,
  diagnoses jsonb DEFAULT '[]'::jsonb,
  plan text,
  ai_generated boolean DEFAULT false,
  ai_confidence jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  data text,
  behavior text,
  intervention text,
  response text,
  goal text,
  problem text,
  mental_status text,
  risk_assessment text,
  rating_scales text,
  treatment_goals text,
  medications_review text,
  follow_up text,
  referrals text,
  note_category USER-DEFINED NOT NULL DEFAULT 'soap'::note_category_enum,
  note_status USER-DEFINED NOT NULL DEFAULT 'draft'::note_status_enum,
  is_locked boolean NOT NULL DEFAULT false,
  finalized_by uuid,
  finalized_at timestamp with time zone,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text])),
  CONSTRAINT visit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT visit_notes_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT visit_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id),
  CONSTRAINT visit_notes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.clinicians(id),
  CONSTRAINT visit_notes_finalized_by_fkey FOREIGN KEY (finalized_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.visit_recordings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid NOT NULL,
  file_path text NOT NULL,
  file_size bigint,
  duration_seconds integer,
  content_type text,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT visit_recordings_pkey PRIMARY KEY (id),
  CONSTRAINT visit_recordings_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT visit_recordings_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.clinicians(id)
);
CREATE TABLE public.visits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  clinician_id uuid NOT NULL,
  appointment_id uuid,
  visit_type USER-DEFINED NOT NULL,
  visit_status USER-DEFINED NOT NULL DEFAULT 'draft'::visit_status,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  location text,
  chief_complaint text,
  last_edited_by uuid,
  last_edited_at timestamp with time zone NOT NULL DEFAULT now(),
  finalized_by uuid,
  finalized_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  note_format text DEFAULT 'soap'::text CHECK (note_format = ANY (ARRAY['soap'::text, 'dap'::text, 'birp'::text, 'girp'::text, 'pirp'::text])),
  CONSTRAINT visits_pkey PRIMARY KEY (id),
  CONSTRAINT visits_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT visits_clinician_id_fkey FOREIGN KEY (clinician_id) REFERENCES public.clinicians(id),
  CONSTRAINT visits_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT visits_last_edited_by_fkey FOREIGN KEY (last_edited_by) REFERENCES public.clinicians(id),
  CONSTRAINT visits_finalized_by_fkey FOREIGN KEY (finalized_by) REFERENCES public.clinicians(id),
  CONSTRAINT visits_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.clinicians(id)
);