-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  changes jsonb,
  ip_address text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  drug_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT cart_items_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES public.otc_drugs(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  participant_ids ARRAY NOT NULL,
  subject character varying,
  conversation_type character varying DEFAULT 'direct'::character varying CHECK (conversation_type::text = ANY (ARRAY['direct'::character varying, 'group'::character varying]::text[])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.doctor_patient_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT doctor_patient_links_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_patient_links_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES auth.users(id),
  CONSTRAINT doctor_patient_links_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES auth.users(id)
);
CREATE TABLE public.doctor_prescriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  duration text NOT NULL,
  instructions text,
  notes text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'processing'::text, 'partially_filled'::text, 'filled'::text])),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  prescription_number text NOT NULL DEFAULT ''::text UNIQUE,
  filled_at timestamp with time zone,
  pharmacist_name text,
  file_url text,
  file_name text,
  medication_name text,
  dosage text,
  refills_allowed integer DEFAULT 0,
  rejection_reason text,
  admin_notes text,
  doctor_name text,
  doctor_phone text,
  doctor_email text,
  practice_name text,
  practice_address text,
  refill_count integer DEFAULT 0,
  refill_limit integer DEFAULT 5,
  last_refilled_at timestamp without time zone,
  is_refillable boolean DEFAULT false,
  refill_status character varying DEFAULT 'active'::character varying,
  CONSTRAINT doctor_prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_prescriptions_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id),
  CONSTRAINT doctor_prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id)
);
CREATE TABLE public.doctor_prescriptions_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_prescription_id uuid NOT NULL,
  medication_name text NOT NULL,
  dosage text,
  quantity integer,
  brand_choice text DEFAULT 'generic'::text CHECK (brand_choice = ANY (ARRAY['brand'::text, 'generic'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  duration text,
  frequency text,
  medication_id uuid,
  price numeric,
  total_amount numeric,
  quantity_filled integer DEFAULT 0,
  CONSTRAINT doctor_prescriptions_items_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_prescriptions_items_doctor_prescription_id_fkey FOREIGN KEY (doctor_prescription_id) REFERENCES public.doctor_prescriptions(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipientemail text NOT NULL,
  subject text NOT NULL,
  templatetype text,
  status text DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text, 'bounced'::text, 'opened'::text, 'clicked'::text])),
  sentat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  failurereason text,
  messageid text UNIQUE,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  orderupdates boolean DEFAULT true,
  prescriptionupdates boolean DEFAULT true,
  promotionalemails boolean DEFAULT false,
  weeklynewsletter boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT email_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  type text NOT NULL CHECK (type = ANY (ARRAY['order_confirmation'::text, 'order_shipped'::text, 'prescription_approved'::text, 'refill_approved'::text, 'refill_rejected'::text, 'password_reset'::text, 'verification'::text, 'custom'::text])),
  subject text NOT NULL,
  htmlcontent text NOT NULL,
  textcontent text,
  variables ARRAY DEFAULT '{}'::text[],
  enabled boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  drug_id uuid NOT NULL,
  drug_type text NOT NULL CHECK (drug_type = ANY (ARRAY['otc'::text, 'prescription'::text])),
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['adjustment'::text, 'purchase'::text, 'sale'::text, 'expiration'::text, 'damage'::text])),
  quantity_change integer NOT NULL,
  quantity_before integer NOT NULL,
  quantity_after integer NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.message_reads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT message_reads_pkey PRIMARY KEY (id),
  CONSTRAINT message_reads_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT message_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  attachment_url character varying,
  attachment_type character varying,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  read_by ARRAY DEFAULT '{}'::uuid[],
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  drug_id uuid NOT NULL,
  drug_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES public.otc_drugs(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_number text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'payment_pending'::text, 'payment_verified'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text])),
  total_amount numeric NOT NULL,
  subtotal_amount numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  shipping_amount numeric DEFAULT 0,
  shipping_address text,
  billing_address text,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  payment_status character varying DEFAULT 'unpaid'::character varying,
  payment_method character varying,
  receipt_url text,
  transaction_id uuid,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT orders_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.otc_drugs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  category text NOT NULL,
  sub_category text NOT NULL,
  manufacturer text,
  sku text NOT NULL UNIQUE,
  quantity_on_hand integer NOT NULL DEFAULT 0,
  reorder_level integer NOT NULL DEFAULT 10,
  reorder_quantity integer NOT NULL DEFAULT 50,
  unit_price numeric NOT NULL,
  cost_price numeric,
  description text,
  indications text,
  warnings text,
  side_effects text,
  dosage text,
  active_ingredient text,
  strength text,
  pack_size text,
  expiration_date date,
  lot_number text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'discontinued'::text, 'out_of_stock'::text])),
  low_stock_alert boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  file_url text,
  category_type character varying DEFAULT 'regular'::character varying CHECK (category_type::text = ANY (ARRAY['regular'::character varying, 'sale'::character varying, 'clearance'::character varying]::text[])),
  sale_price numeric,
  sale_discount_percent integer,
  sale_start_date timestamp with time zone,
  sale_end_date timestamp with time zone,
  CONSTRAINT otc_drugs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_holder character varying NOT NULL,
  bank_name character varying NOT NULL,
  account_number character varying NOT NULL,
  routing_number character varying,
  iban character varying,
  swift_code character varying,
  additional_instructions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tax_type text DEFAULT 'inclusive'::text CHECK (tax_type = ANY (ARRAY['none'::text, 'inclusive'::text])),
  tax_rate numeric DEFAULT 15,
  kingston_delivery_cost numeric DEFAULT 0,
  CONSTRAINT payment_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prescription_drugs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  category text NOT NULL,
  sub_category text NOT NULL,
  manufacturer text,
  sku text NOT NULL UNIQUE,
  quantity_on_hand integer NOT NULL DEFAULT 0,
  reorder_level integer NOT NULL DEFAULT 20,
  reorder_quantity integer NOT NULL DEFAULT 100,
  unit_price numeric NOT NULL,
  cost_price numeric,
  description text,
  indications text,
  warnings text,
  side_effects text,
  dosage text,
  active_ingredient text,
  strength text,
  pack_size text,
  requires_refrigeration boolean DEFAULT false,
  controlled_substance boolean DEFAULT false,
  expiration_date date,
  lot_number text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'discontinued'::text, 'out_of_stock'::text])),
  low_stock_alert boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  file_url text,
  category_type character varying DEFAULT 'regular'::character varying CHECK (category_type::text = ANY (ARRAY['regular'::character varying, 'sale'::character varying, 'clearance'::character varying]::text[])),
  sale_price numeric,
  sale_discount_percent integer,
  sale_start_date timestamp with time zone,
  sale_end_date timestamp with time zone,
  CONSTRAINT prescription_drugs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prescription_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  medication_id uuid,
  brand_choice text DEFAULT 'generic'::text CHECK (brand_choice = ANY (ARRAY['brand'::text, 'generic'::text])),
  quantity integer NOT NULL,
  price numeric,
  notes text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  medication_name text,
  dosage text,
  quantity_filled integer DEFAULT 0,
  total_amount integer,
  doctor_prescription_id uuid,
  CONSTRAINT prescription_items_pkey PRIMARY KEY (id),
  CONSTRAINT prescription_items_doctor_prescription_id_fkey FOREIGN KEY (doctor_prescription_id) REFERENCES public.doctor_prescriptions(id),
  CONSTRAINT prescription_items_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id)
);
CREATE TABLE public.prescriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  doctor_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'processing'::text, 'partially_filled'::text, 'filled'::text])),
  file_url text NOT NULL,
  quantity integer,
  refills_allowed integer DEFAULT 0,
  notes text,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  prescription_number text NOT NULL DEFAULT ''::text UNIQUE,
  doctor_name text,
  doctor_phone text,
  doctor_email text,
  practice_name text,
  practice_address text,
  admin_notes text,
  filled_at timestamp with time zone,
  pharmacist_name text,
  refill_count integer DEFAULT 0,
  refill_limit integer DEFAULT 5,
  last_refilled_at timestamp without time zone,
  is_refillable boolean DEFAULT false,
  refill_status character varying DEFAULT 'active'::character varying,
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id),
  CONSTRAINT prescriptions_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.users(id)
);
CREATE TABLE public.refill_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  requested_at timestamp without time zone NOT NULL DEFAULT now(),
  approved_at timestamp without time zone,
  approved_by uuid,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  notes text,
  reason text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT refill_requests_pkey PRIMARY KEY (id),
  CONSTRAINT refill_requests_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id),
  CONSTRAINT refill_requests_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id),
  CONSTRAINT refill_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.refills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  refill_number integer NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'requested'::text, 'approved'::text, 'rejected'::text])),
  requested_at timestamp with time zone,
  approved_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT refills_pkey PRIMARY KEY (id),
  CONSTRAINT refills_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id),
  CONSTRAINT refills_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  name text NOT NULL,
  content text NOT NULL,
  is_approved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT testimonials_pkey PRIMARY KEY (id),
  CONSTRAINT testimonials_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.users(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['payment'::character varying, 'refund'::character varying, 'adjustment'::character varying, 'credit'::character varying]::text[])),
  method character varying NOT NULL CHECK (method::text = ANY (ARRAY['card'::character varying, 'bank_transfer'::character varying, 'cash'::character varying, 'insurance'::character varying, 'wallet'::character varying]::text[])),
  amount numeric NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  reference_id character varying,
  description text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone text,
  address text,
  city text,
  state text,
  zip text,
  avatar_url text,
  date_of_birth date,
  license_number text,
  license_state text,
  specialty text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text,
  role text NOT NULL DEFAULT 'patient'::text CHECK (role = ANY (ARRAY['patient'::text, 'admin'::text, 'doctor'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);